# Generated by Django 3.1.1 on 2020-11-10 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20201110_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='poster',
            new_name='user',
        ),
    ]
