# Generated by Django 3.1.1 on 2020-11-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_post_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='edited',
            field=models.IntegerField(default=0),
        ),
    ]
